# Generated by Django 6.0.2 on 2026-03-07 08:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
